### ISSUE TITLE
Adding user to a group short circuts

### ISSUE THREAD

**Issue by fitzsimonsdevin** [dabit3/full-stack-serverless-code#45]
I'm working through this section of the book.
![image](https://user-images.githubusercontent.com/51139414/97812532-0f4aa680-1c3f-11eb-80d1-09eab7d27094.png)

 When I choose add user to group as suggested it just quits, without letting me configure this and create the function. 
![image](https://user-images.githubusercontent.com/51139414/97812432-89c6f680-1c3e-11eb-949a-d03fdaddfcfc.png)
I checked the errata [here](https://www.oreilly.com/catalog/errata.csp?isbn=0636920286585) and didn't see anything. Do I perhaps have my permissions wrong in the CLI? Or perhaps has something changed in the cli. I'm using `4.31.1`. Thanks for the book and all the articles, tweets and such.

**Comment by fitzsimonsdevin** [comment]
Oh man... 

This selection needs a spacebar to choose and enter selects and I just missed it. How silly. Sorry.

**Comment by wispyco** [comment]
I literally did the exact same thing, thanks for posting this I deleted and readded the auth like 3 times
